"""SSD sampling data generation — produces JSONL training data via vLLM offline inference.

Generates a self-contained Python script that:
1. Loads problems from LiveCodeBench v6
2. Runs vLLM offline inference to generate code solutions
3. Writes results as JSONL for downstream SFT training
"""
from __future__ import annotations

import json
from typing import Any

_SAMPLING_SCRIPT_TEMPLATE = '''\
#!/usr/bin/env python3
"""SSD Sampling Script - generated by auto-coder-trainer."""

import json
import sys
from pathlib import Path

from datasets import load_dataset
from transformers import AutoTokenizer
from vllm import LLM, SamplingParams

def main():
    model_name = {model_name!r}
    output_path = Path({output_path!r})
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Load dataset
    ds = load_dataset({dataset!r}, split={dataset_split!r}, trust_remote_code=True)
    print(f"Loaded {{len(ds)}} problems")
{filter_lines}
    # Initialize vLLM
    llm = LLM(model=model_name, tensor_parallel_size={tensor_parallel_size})
    tokenizer = AutoTokenizer.from_pretrained(model_name)

    PROMPT_TEMPLATE = """You will be given a question (problem specification) and will generate a correct Python program that matches the specification and passes all tests. You will NOT return anything except for the program.

Question: {{{{problem_description}}}}

Read the inputs from stdin solve the problem and write the answer to stdout (do not directly test on the sample inputs). Enclose your code within delimiters as follows. Ensure that when the python program runs, it reads the inputs, runs the algorithm and writes output to STDOUT.
```python
  # YOUR CODE HERE
```"""

    stop_token_ids = [tokenizer.eos_token_id] if tokenizer.eos_token_id is not None else []
    all_examples = list(ds)
    n_written = 0

    for i in range({n_samples}):
        seed = {seed} + i
        prompts = []
        for example in all_examples:
            prompt_text = PROMPT_TEMPLATE.format(problem_description=example.get("question_content", example.get("prompt", "")))
            messages = [{{"role": "user", "content": prompt_text}}]
            templated = tokenizer.apply_chat_template(
                messages, tokenize=False, add_generation_prompt=True
            )
            prompts.append(templated)

        sampling_params = SamplingParams(
            max_tokens={max_tokens},
            temperature={temperature},
            top_p={top_p},
            top_k={top_k},
            seed=seed,
            stop_token_ids=stop_token_ids,
        )

        print(f"Generating repeat {{i+1}}/{{{n_samples}}}...")
        outputs = llm.generate(prompts, sampling_params)

        for example, output in zip(all_examples, outputs):
            completion = output.outputs[0].text
            if not completion.strip():
                continue
            entry = {{
                "messages": [
                    {{"role": "user", "content": example.get("question_content", example.get("prompt", ""))}},
                    {{"role": "assistant", "content": completion}},
                ],
                "metadata": {{
                    "task_id": example.get("question_id", ""),
                    "difficulty": example.get("difficulty", ""),
                    "repeat_index": i,
                    "seed": seed,
                }},
            }}
            with open(output_path, "a") as f:
                f.write(json.dumps(entry) + "\\n")
            n_written += 1

    print(f"Wrote {{n_written}} examples to {{output_path}}")

if __name__ == "__main__":
    main()
'''


def generate_sampling_script(config: dict[str, Any]) -> str:
    """Generate a self-contained Python script for vLLM sampling.

    The produced script can be submitted to SLURM or run standalone.
    It outputs one JSONL file where each line is a training example
    with ``messages`` (user prompt + assistant completion).
    """
    model_name = config.get("model_name", "")
    output_path = config.get("output_path", "sample_data.jsonl")
    dataset = config.get("dataset", "livecodebench/code_generation_lite")
    dataset_split = config.get("dataset_split", "test")
    dataset_filter = config.get("dataset_filter", {})
    temperature = config.get("temperature", 0.9)
    top_p = config.get("top_p", 0.8)
    top_k = config.get("top_k", 20)
    max_tokens = config.get("max_tokens", 65536)
    n_samples = config.get("n_samples", 10)
    seed = config.get("seed", 0)
    tensor_parallel_size = config.get("tensor_parallel_size", 4)

    filter_lines = ""
    if dataset_filter.get("contest_date"):
        dates = dataset_filter["contest_date"]
        filter_lines = (
            f'\n    # Filter by contest date\n'
            f'    target_months = {dates!r}\n'
            f'    ds = ds.filter(lambda x: x["contest_date"][:7] in target_months)\n'
            f'    print(f"Problems after date filter: {{{{len(ds)}}}}")\n'
        )

    return _SAMPLING_SCRIPT_TEMPLATE.format(
        model_name=model_name,
        output_path=output_path,
        dataset=dataset,
        dataset_split=dataset_split,
        filter_lines=filter_lines,
        tensor_parallel_size=tensor_parallel_size,
        n_samples=n_samples,
        seed=seed,
        max_tokens=max_tokens,
        temperature=temperature,
        top_p=top_p,
        top_k=top_k,
    )


def format_sample_output(
    prompt: str,
    completion: str,
    metadata: dict[str, Any],
) -> dict[str, Any] | None:
    """Format a single sampling result into a training-ready dict.

    Returns ``None`` if the completion is empty.
    """
    if not completion.strip():
        return None

    return {
        "messages": [
            {"role": "user", "content": prompt},
            {"role": "assistant", "content": completion},
        ],
        "metadata": metadata,
    }
